apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: appsody-build-pipeline
spec:
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: appsody-build
      taskRef:
        name: appsody-build-push-deploy-task
      resources:
        inputs:
        - name: git-source
          resource: git-source
        - name: docker-image
          resource: docker-image
      params:
      - name: app-deploy-file-name
        value: app-deploy.yaml
