apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: orders-pipeline-quay-
spec:
  serviceAccountName: appsody-sa
  timeout: "1h0m0s"  
  pipelineRef:
    name: build-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: orders-source
    - name: docker-image
      resourceRef:
        name: orders-image-external
