apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ibm-quay-cve-check
  annotations:
    description: Connects to Quay and queries an image for CVE's
    app.openshift.io/description: Connects to Quay and queries an image for CVE's
    app.openshift.io/vcs-uri: https://github.com/IBM/ibm-garage-tekton-tasks
    app.openshift.io/vcs-ref: master
  labels:
    version: 0.0.0
spec:
  params:
    - name: image
      default: ""
    - name: CVE_SCAN_IMAGE
      default: registry.redhat.io/ubi8
  steps:
    - name: image-scan
      image: $(params.CVE_SCAN_IMAGE)
      script: |
        set -x
        IMAGE="$(params.image)"
       